### ISSUE TITLE
[Feature Bug & Enhancement] Check for Updates

### ISSUE THREAD

**Issue by ramphex** [rivenmedia/riven-frontend#51]
**Describe the bug**
Bug: Check for Updates returns in an error instead of checking for an update.
Enhancement Request: If an update is available, display the changelog including breaking changes (example: new necessary changes to the docker-compose file) to prevent users from just issuing docker-compose pull, docker-compose up -d and ending up with broken setups. Also since containers are now split, it should check for versions of front-end and back-end.

**To Reproduce**

1. Go to 'Settings/About'
2. Click on 'Check for Updates'
3. See error

**Expected behavior**
Display a message indicating the setup is up to date, or whether there is a new version available and what it is.

**Comment by AyushSehrawat** [comment]
Done

**Comment by ramphex** [comment]
Broken again, front end 0.8.1 and back end 0.10.1. About page shows "Version 0.9.2" and clicking check for update advises that there is an update and to check github for changelog.

**Comment by AyushSehrawat** [comment]
Will look into it

**Comment by AyushSehrawat** [comment]
looks good to me, try and lmk if it happens again

**Comment by ramphex** [comment]
On latest for both front end and back end, about still shows current is 0.9.2 and an update is available. Is it reading the version from settings.json? Maybe the backend fails to update the json with the current version when updating and not installing fresh.

**Comment by AyushSehrawat** [comment]
![image](https://github.com/user-attachments/assets/f771eb97-eb21-497c-9fc6-c1cdf8636de6)

it is fine for me. ig back up the settings.json and delete data folder and db. then pull latest compose image and try

**Comment by ramphex** [comment]
Someone else in Discord reported that they're having the same issue, deleting the database and data folder shouldn't be the solution each time there's a bug though. The question should be why is Riven back-end not updating the settings.json "version" line on Riven updates (assuming that's where the front-end gets that version number).

**Comment by AyushSehrawat** [comment]
> Someone else in Discord reported that they're having the same issue, deleting the database and data folder shouldn't be the solution each time there's a bug though. The question should be why is Riven back-end not updating the settings.json "version" line on Riven updates (assuming that's where the front-end gets that version number).

it updated for me 🤔 . There is code in backend to update. @dreulavelle ^^
i get settings number and then the latest version from github repo

**Comment by ramphex** [comment]
I just pulled 0.10.5 back end and 0.11.0 front-end release from yesterday and the UI still says 0.9.2 despite the logs saying 0.10.5.

<img width="763" alt="Screenshot 2024-08-20 at 14 35 50" src="https://github.com/user-attachments/assets/e7ed595a-2e0c-458f-99e8-2ffa48950221">

<img width="1101" alt="Screenshot 2024-08-20 at 14 36 04" src="https://github.com/user-attachments/assets/e0ceaa2a-db91-4f12-b027-ecaf7c2882ff">

**Comment by AyushSehrawat** [comment]
> I just pulled 0.10.5 back end and 0.11.0 front-end release from yesterday and the UI still says 0.9.2 despite the logs saying 0.10.5.
> 
> <img alt="Screenshot 2024-08-20 at 14 35 50" width="763" src="https://private-user-images.githubusercontent.com/43665314/359604250-e7ed595a-2e0c-458f-99e8-2ffa48950221.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxNzk1MjYsIm5iZiI6MTcyNDE3OTIyNiwicGF0aCI6Ii80MzY2NTMxNC8zNTk2MDQyNTAtZTdlZDU5NWEtMmUwYy00NThmLTk5ZTgtMmZmYTQ4OTUwMjIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIwVDE4NDAyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk4OTYzMDlkMTZiYWEwMDA3NDAzZmJlNGJhNTI4NmNkMWI0MjQyODE0OTZiY2M0Zjc0ODJhOGQ1YjgzYjAyNzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VMxa2oOTLMLXGWoZoRKVm4jweM-g4or8EQwukOrXpGw"> <img alt="Screenshot 2024-08-20 at 14 36 04" width="1101" src="https://private-user-images.githubusercontent.com/43665314/359604318-e0ceaa2a-db91-4f12-b027-ecaf7c2882ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxNzk1MjYsIm5iZiI6MTcyNDE3OTIyNiwicGF0aCI6Ii80MzY2NTMxNC8zNTk2MDQzMTgtZTBjZWFhMmEtZGI5MS00ZjEyLWIwMjctZWNhZjdjMjg4MmZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIwVDE4NDAyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiM2M2MWZjZjFhNTQwNTUzN2VlYmFiNTAyMmQ0ZjBlZWY4ZDllNjk1YWY5YjFjOGFkYzhmNGUxZGRmZWY3MTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.a4s2hGd9TgwGOJxr0ZtJSVAwdxg1lZlYlwYfapnmGaE">
> Also this
> 
> <img alt="Screenshot 2024-08-20 at 14 39 19" width="494" src="https://private-user-images.githubusercontent.com/43665314/359605280-6adf5bf0-29c0-4973-bb04-f2b09f1c0215.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxNzk1MjYsIm5iZiI6MTcyNDE3OTIyNiwicGF0aCI6Ii80MzY2NTMxNC8zNTk2MDUyODAtNmFkZjViZjAtMjljMC00OTczLWJiMDQtZjJiMDlmMWMwMjE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIwVDE4NDAyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhM2E1ODM0MTdhNzM0YjExOGJkOWY3NzU5ZjY2MDk2MDk3ZDAzOWI1NWU4NmQyZWFmNDNjNDhiZDVjOTdiYzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Opx0WaqfJTIQveaHSLgIb26XsNESDqqRITvZDHPI3z4">
> says file was updated when pulled, but inside
> 
> <img alt="Screenshot 2024-08-20 at 14 40 01" width="481" src="https://private-user-images.githubusercontent.com/43665314/359605440-7c2241c2-d54b-47d7-bdf9-fb80da0915cc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxNzk1MjYsIm5iZiI6MTcyNDE3OTIyNiwicGF0aCI6Ii80MzY2NTMxNC8zNTk2MDU0NDAtN2MyMjQxYzItZDU0Yi00N2Q3LWJkZjktZmI4MGRhMDkxNWNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIwVDE4NDAyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ5Nzg5NzA0YTFmMjIxODAyYTllZDBmNzk4NTU3YzcwNTI2NTZmNTE2ZjIzNTJiYmI0MDU5MmM4MDc1Zjc0YjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Mi3AuxTB2HY3w0M00BL8e1CSl04hYuy42CJ_YuqL36I">

seems some backend bug. i have pinged @dreulavelle
